# Generated by Django 4.0.2 on 2022-03-23 16:03

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('headcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('type', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('email_verification', models.BooleanField(default=False)),
                ('college_verification', models.BooleanField(default=False)),
                ('college_id', imagekit.models.fields.ProcessedImageField(upload_to='uploads/')),
                ('college_document', imagekit.models.fields.ProcessedImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sem', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
                ('last_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_teacher', to='api.branch')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_teacher', to='api.college')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_suggestion', to='api.college')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usn', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=255)),
                ('profile_pic', imagekit.models.fields.ProcessedImageField(upload_to='uploads/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_student', to='api.branch')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_student', to='api.college')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_community', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('sem', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_class', to='api.branch')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_class', to='api.college')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='college_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_branch', to='api.college'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.IntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='api.class')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_attendance', to='api.college')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('streetname', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_address', to='api.college')),
            ],
        ),
    ]
