# Generated by Django 4.0.2 on 2022-03-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='type',
            field=models.CharField(choices=[('Affiliated', 'Affiliated'), ('Deemed', 'Deemed')], max_length=255),
        ),
    ]
