# Generated by Django 4.0.2 on 2022-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_scholarship_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
