# Generated by Django 4.0.2 on 2022-03-26 04:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
