# Generated by Django 4.0.2 on 2022-03-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scholarship_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_community', to='api.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
