# Generated by Django 4.0.3 on 2023-01-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_qr_user_alter_document_user_userinfo_track_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qr',
        ),
    ]
