# Generated by Django 4.0.3 on 2023-01-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userinfo_age_userinfo_dob_userinfo_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
