# Generated by Django 4.0.3 on 2023-01-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userinfo_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
